export const SUPABASE_URL = "https://zhoueuqnmtjskbiwnkzu.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpob3VldXFubXRqc2tiaXdua3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk1MjMzNDQsImV4cCI6MjA5NTA5OTM0NH0.7TZmr048orxLcAdqQrOaihvfAOEw4xGYpMaZviw-z-g";
